{% set version = "1.1.1" %}

package:
  name: sep
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/sep/sep-{{ version }}.tar.gz
  sha256: 9548af5f13ea9bbfc3a76d15d809b7df72c31442f0c47e26daf9052c92c5ad73

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy
    - cython
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - sep

about:
  home: https://github.com/kbarbary/sep
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: licenses/LGPL_LICENSE.txt
  summary: Astronomical source extraction and photometry library
  description: |
    SEP makes the core algorithms of Source Extractor available as a
    library of stand-alone functions and classes. These operate directly
    on in-memory arrays (no FITS files or configuration files). The code
    is derived from the Source Extractor code base (written in C) and aims
    to produce results compatible with Source Extractor whenever possible.
  doc_url: http://sep.readthedocs.io/
  dev_url: https://github.com/kbarbary/sep

extra:
  recipe-maintainers:
    - kbarbary
    - mwcraig
