{% set version = "1.4.1" %}

package:
  name: sep
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/s/sep/sep-{{ version }}.tar.gz
  sha256: a0c8324ab66ee716080472cb212e4303e6c3e33b0d43763075b20d4cab793b25

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - setuptools
    - numpy
    - cython
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - sep

about:
  home: https://github.com/kbarbary/sep
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: licenses/LGPL_LICENSE.txt
  summary: Astronomical source extraction and photometry library
  description: |
    SEP makes the core algorithms of Source Extractor available as a
    library of stand-alone functions and classes. These operate directly
    on in-memory arrays (no FITS files or configuration files). The code
    is derived from the Source Extractor code base (written in C) and aims
    to produce results compatible with Source Extractor whenever possible.
  doc_url: http://sep.readthedocs.io/
  dev_url: https://github.com/kbarbary/sep

extra:
  recipe-maintainers:
    - kbarbary
    - mwcraig
