travis:
  secure:
    BINSTAR_TOKEN: hjoZqE9u//pPw4Jb8ogknPpXR1XXKaryV4YhNogilPXY9oM6lVCzcLAYd/XOKbv9vYdVZVVbRrCksxRnALkUqDr6uEDBqeDIBodJ04CE8Xj/675DBvPdVNz54wd0QrQpI0rzV/qbTx8H7IeL5YhBPIHnNVeTcYHjnl80RJxnhihiIQTFFs4wq8S5o5GAG7J2ABIRMf7/lun5ZxKJgE2jOI22cIP8Tx5Z7QhxWqOgPwHhGFoUR+tnO6z4XH8lrw5JP2BAPIsx0ixN2nj+a84Jk0SkoJVqCKGvlZbuboiX623gctqyAV805i3yJJ2IeLCUc3FbTfIbXzaQ4DreSdnoa5PhZGAGer3wJw9NBv0iVwz/nOek0Ps40ZbV84x6IAkd9oHjcVtw6XqjRrXCTvI4h4FnGJTkcLw83UewMlwf3NnAGVPxHSUm9st0ifkd0HC+1JapaQGrulmoe8WMV9O+x8zzZUZD4SqJ5IFtw58/DBaujZmRLWGMJ2PzHlgQ7HwC8sSpinG6iW286ZYtVbxN4m2YFV2bF+pRDq+58hVMB+GFzRflB2r8nyFAjOjNDgehRWPlXGpVzmqMVb+V5CorvCuWd3GBwpZftQwAIqAGpIzE4zHBf6kMNw/GAT5TNlWPmR1T+gqvGPzrqu6YQfda+U9C/5EonsvorSrGl4eYrTI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
conda_forge_output_validation: true
