travis:
  secure:
    BINSTAR_TOKEN: bTPG7YguXyWHvZ/VQ0sqMqBUcPcl+7Ia653r3ry5L+2o3UQDkURbRpQNVzF5MA4D+Q9mBSZQSoUyynFsH80nbmkOeW08JaJtUnImvsEIq5sec9mL+mwWfQ4HwC+nQQZmKEOcSvYWPh+OD+XqJ3axnFyUxg3NjLwGuD8gQUC+Qiw3VVT5Cya5hCLMcTPaPY3wQuTLU79mly5JA1giFLfzmGPZif0MgXuWsf7uKhJLBWaCNTZezMZ1c6AB5EimtPHQf7Un3IO9Rz+meMLGqYrhNABUatduhgHvKEZMfsra8DmDh0fJ7qWV6XV+k+F1pc5Mu5cBU/MR7winhfE1LqnG32GZW8mjU//fon8nYiuq1N5kUPJElvpuLlbYL9awhnrDLCZffRwTVvjD5dHAaMPeF/ZS1j9DVq6VZdPU7J/rjc2pQ3PFCI/PtMD00qJGFZH7a6f04D+hlvgE5cJo1zRQQf1Smz4OsuJQqfECcommnYxYLocmqa021vcvG3TJrNLPhjiSxTNl7CTzplu8MzBVZ0ZO5xl84uWSyp/uG7faQmXSPK4sCAHlfaFRv6YeCsMhCvw+qn+VqSZSPqJVKvaHYJ98ed+YlBamzPeat0q9Ctz7roUIaGw5jL5WRIki4yJOWODkGb31YjHzqkoUMbarTMoKY0X2K6sDpTPGqnTOA4c=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
